version: "3"
services:
    rabbitmq:
        ports:
            - "5672:5672"
        volumes:
                - .:/code
        image: rabbitmq:3
    postgresql:
        image: mdillon/postgis
        restart: on-failure
        volumes:
            - .:/code/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: isd
            POSTGRES_PASSWORD: isd
            POSTGRES_DB: isd
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: isd
            MYSQL_DATABASE: isd
            MYSQL_USER: isd
            MYSQL_PASSWORD: isd
    hekpuller:
        build: hekpuller/.
        volumes:
            - .:/code
        links:
            - rabbitmq
            - postgresql
        ports:
            - "1278:1278"
        depends_on:
            - "rabbitmq"
            - "postgresql"
        environment:
            POSTGRE_SQL_DB_HOST: postgresql:5432
            POSTGRES_USER: isd
            POSTGRES_PASSWORD: isd
            POSTGRES_DB: isd